### ISSUE TITLE
Detailed description of parameters and topics

### ISSUE THREAD

**Issue by tuloski** [evocortex/optris_drivers#21]
Hi,
is there a detailed description of the parameters in the .launch file and in the .xml configuration?
For example I don't uderstand the difference of temperature min-max in the .xml and temperature min-max in the .launch.
Also how the raw data is saved on the thermal_image topic is not clear. The documentation says:"Temperature data is encoded as: float t = (float)(data - 1000) / 10.f.", but what is data? Is the temperature in the defined range scaled into 0-256?
I checked the topic and there are values between 0 and 256 (8 bit) alternated by 4. What is the 4 for?

**Comment by stefanmay** [comment]
Dear tuloski,

you can find information about the parameters directly in the mentioned
files as comments. The parameters temperatureMin and temperatureMax in
the launch file describe the values, which are used to convert the
temperature image to a palette image. Temperatures below temperatureMin
are converted into the same color, as well as temperatures higher than
temperatureMax. This is just a displaying issue. The temperature values
in the xml file state the calibration range.

Temperatures are represented as unsigned short value. That is why you
get these alternation of 4 and 2xx. If you read it correctly your
example value is: 1024 + 255 = 1279
=> t = (1279 - 1000) / 10 = 27.9°C

Best regards,

   Stefan May

Am 19.01.2018 um 14:16 schrieb tuloski:

**Comment by tuloski** [comment]
> Temperatures are represented as unsigned short value. That is why you
get these alternation of 4 and 2xx. If you read it correctly your
example value is: 1024 + 255 = 1279
=> t = (1279 - 1000) / 10 = 27.9°C

Sorry, I'm not understanding this part. Where is the 1024 coming from? And what is the 4? A multiplier?
For example I have the calibration range -20°C / 100°C. How is the 100°C represented and how is the -20°C represented? Using 8 bits there are only 256 representation, so is the resolution around 120/256 (around half degree)?

Thanks

**Comment by stefanmay** [comment]
you are interpreting the data wrongly. This is a 16 bit representation
(unsigned short), not 8 bit.

-20°C => 800
100°C => 2000

1024 = 2^10

Am 21.01.2018 um 13:01 schrieb tuloski:

**Comment by jeanpul** [comment]
Hi,

I'm also interested on how obtaining temperature value from the yuv422 format. Currently, I'm decoding the data using unsigned short value (16bits, BigEndian), then I apply the formula : 
t = (getUint16 - 1000) / 10 then the values are very high, nearly 100x the correct values.

For example I have a getUInt16 value on the image center which is 35325 then the formula give me 3432.5 whereas the Optris PI connect software give me 28.60

When I try to display my temperature values using false color (i.e between [0;1]), then my image is nearly correct so I think I'm missing something.

Could you provide us some real example, or could you give us access to the code _iBuilder.convertTemperatureToPaletteImage or _iBuilder.yuv422torgb24 ?

Thanks

**Comment by tuloski** [comment]
Ok, now I got it...I feel dumb :)

@jeanpul are you sure you're parsing correctly the data. Is your getUint16 correct?

**Comment by stefanmay** [comment]
you cannot use the yuv422 values directly. First, a processing of the
data needs to be performed. Please use the callback methods to get
temperature data.


Am 22.01.2018 um 20:05 schrieb jeanpul:

**Comment by jeanpul** [comment]
Hi stefanmay,

Could you, please provide us the code to process directly the yuv422 ?
Do you have any sample data that could be used with your sdk and your examples ?

Thanks

**Comment by stefanmay** [comment]
Dear jeanpul,

I cannot provide the code. It contains private property of a third
party. You need to use the SDK.

What do you mean with sample data? A bag file of the yuv422 data stream?
You can find examples included in the SDK under
/usr/share/doc/libirimager/

Best regards,

   Stefan May

Am 23.01.2018 um 12:19 schrieb jeanpul:

**Comment by jeanpul** [comment]
Dear Stefan,

I try to use the SDK & samples from /usr/share/doc/libirimager/
but then I obtain the same temperature value maybe my input data is wrong. Here
is the link to my frame [http://root.innovisite.com/test/out.raw](url) (it's yuv422 382x289)

Using this frame as input, the SDK getTemperatureAt(191,144) returns 6390.5 whereas the OptiPI Connect returns 28.60 [http://root.innovisite.com/test/out.raw/Screenshot_001.jpg](url)

Regards,

Fabien

**Comment by stefanmay** [comment]
Dear Fabien,

please send this issue to the info address of evocortex. Your problem is
not related to the ROS interface. First, you need to make the SDK
working. Please check the information here:
http://documentation.evocortex.com/libirimager2/html/index.html

If you post a message to the info address, please provide details about
your system and installation procedure (since you have BigEndian, I
assume, this is not a standard linux distribution). It is also needed to
attach a log file. You can generate it with:
IRLogger::setVerbosity(IRLOG_DEBUG, IRLOG_OFF);

Best regards,

   Stefan

Am 23.01.2018 um 14:02 schrieb jeanpul:

**Comment by tuloski** [comment]
I was able to get the temperature data from the raw /thermal_image.
But I have a few questions:

- I tried to get the temperature of my hand, and the highest was 30 degree, which is quite off the specifications error (2 degrees or 2%). Is it normal?
- I tried to put an object with temperature > 200 degrees and with temperature range setting -20/100. And the highest temperature I get is 124. Why out of range?
- I tried to set the range 150-900 degrees, with the soldering station in the frame (>400 degrees) and I still get the 124 degrees. Aren't the ranges working?

thanks

**Comment by stefanmay** [comment]
please find my answers below.

Am 25.01.2018 um 11:45 schrieb tuloski:
> I was able to get the temperature data from the raw /thermal_image.
> But I have a few questions:
> 
>   * I tried to get the temperature of my hand, and the highest was 30
>     degree, which is quite off the specifications error (2 degrees or
>     2%). Is it normal?
What do you expect? How can you know the exact temperature of your hand?
30 degrees sounds plausible to me. What is the temperature of your head
or or an area in you mouth.

>   * I tried to put an object with temperature > 200 degrees and with
>     temperature range setting -20/100. And the highest temperature I get
>     is 124. Why out of range?
If you configure the temperature range as -20 to 100, you won't get
higher temperatures than 12x degrees.

>   * I tried to set the range 150-900 degrees, with the soldering station
>     in the frame (>400 degrees) and I still get the 124 degrees. Aren't
>     the ranges working?
Yes, they work, but without any detailed information about your setting,
there is no chance to see where your problem is located. Am I right,
that this is not related to ROS? You work with the examples of the SDK?
In that case I would close this issue. Please use the info-address of
evocortex.

**Comment by tuloski** [comment]
No I'm working with ROS, @jeanpul is working with the SDK.

In ROS I changed the setting in both the .xml and the .launch to have the 150-900 range. And I was getting for a 400 degree item 124.
BUT now I tried to call the service set_temperature_range and that worked.
So aren't the parameters in the .xml enough?

**Comment by stefanmay** [comment]
you are right, it seems that the parameter is not respected in the
node's constructor. You might add a line #10 like:
_imager.setTempRange(params.tMin, params.tMax);

We will test this and push an update soon.

Am 25.01.2018 um 13:03 schrieb tuloski:

**Comment by stefanmay** [comment]
Dear tuloski,

I've checked your issue with the newest SDK (3.0.1) and ROS version.
I've managed to get all temperature configurations running. I measured
temperatures above 125°C. Is it possible, that you have not uncommented
the temperature values in the xml file? By default, this section is
commented. You need to remove "" that surrounds this part.

If you still have a problem with it, I need a detailed bug report. Would
you please send me the log file, your configuration file and your system
information (architecture, package versions, etc.).

Best regards,

   Stefan May

Am 25.01.2018 um 13:03 schrieb tuloski:

**Comment by stefanmay** [comment]
Dear Albeiro Jimenez,

this is only possible, if you know the used scale and palette
afterwards. From only an image, you cannot recover the temperatures. I
recommend to store also the temperatures as pseudo-image (that you do
not need to display).

Best regards,

   Stefan May

Am 21.10.18 um 20:24 schrieb AlbeiroJimenez:

**Comment by AlbeiroJimenez** [comment]
Hi, Stefan.

Thanks for fast answer. I tried it.
