### ISSUE TITLE
Flag issue

### ISSUE THREAD

**Issue by selvirangarajan** [evocortex/optris_drivers#27]
Hi,

We are really close to our release and found this critical issue with the camera. Our linux application uses two cameras and streaming from both. The issue is, we misses too many frames from either camera at random times with 4.1.1 SDK. I tried the 6.0.0. SDK whether it helps. But the issue still appears, with irimager_twin_show example, one of the camera frames are corrupted or empty. 

Whenever the issue appears, here is the error am seeing from the example application. 

ERROR [OpFlag.cpp:376] @ 35.6768s :ImagerError_FlagTooShort
ERROR [OpFlag.cpp:376] @ 140.915s :ImagerError_FlagTooShort
ERROR [OpFlag.cpp:376] @ 186.023s :ImagerError_FlagTooShort

It would be great, If you can suggest any flag setting etc., that would quickly help.  
Please provide your input.

**Comment by selvirangarajan** [comment]
Hi, any suggestions to get rid of this error?

**Comment by stefanmay** [comment]
Your error description lacks of information. Please provide information about the platform you are using. Otherwise, It is difficult to help you. The error you posted normally states that the frame rate of the loop that is triggering the processing method, is too slow.

**Comment by selvirangarajan** [comment]
I am testing it with libirimager-x.x.x-amd64 version . This was observed on our product based on armhf too. The issue is reproducible with 4.1.1 as well 6.0.0 imager direct SDK. 

 ·         Target System  
o   processor architecture (X86-64)

o   operating system (Ubuntu 14.04)

·         Camera Model + Serial Number + Firmware version = Optris - 18104018 - 3008, Optris - 18094031 - 3008. 

·         IR Imager Direct-SDK Version (4.1.1,6.0.0)

Please let me know if any more information is required.  To explain the issue again, we see corrupted or frame filled with high/low temp values at random intervals from one of the cameras. (Our setup uses two cameras). Thank you

**Comment by stefanmay** [comment]
The information I need is about the loop which calls the process method. If this loop is too slow, or e.g. if you do intensive calculations in the callback routines, the flag procedure cannot be handled. You need to post the code snipped, in which process is called as well as the callback routines.
Btw. Ubuntu 14.04. is not supported anymore (April 2019 was end of life).

**Comment by selvirangarajan** [comment]
Thank you for the quick response. sorry, it was ubuntu 16.04.  This issue i reproduced with the imager sdk example application. Please find it attached.

[irimagerTwinShow.tar.gz](https://github.com/evocortex/optris_drivers/files/3254744/irimagerTwinShow.tar.gz)
[1.xml.tar.gz](https://github.com/evocortex/optris_drivers/files/3254748/1.xml.tar.gz)

 The shutter flag settings are auto, min and max interval as 15secs.

**Comment by stefanmay** [comment]
I tested the twin show application on an x86_64 platform and was able to reproduce your issue, but only if I attach both cameras to the same USB hub. You need to attach both cameras to different USB host chips. The IR imagers claim almost the full bandwidth of a USB 2.0 interface. Two cameras cannot be driven on the same USB 2.0 interface. I hope this resolves your issue. Please give me a feedback.
