### ISSUE TITLE
where is the optris_imager.yaml?

### ISSUE THREAD

**Issue by brianFruit** [evocortex/optris_drivers#28]
![image](https://user-images.githubusercontent.com/4044934/59457366-1fa17d80-8dcd-11e9-9b44-e20781701cee.png)

We recently bought the Optris Xi 400 and want to integrate it into ROS in a Linux OS. I followed the README and was able to catkin_make the package. However, when I run the optris_drivers.launch, it sends out a warning saying my camera_info_url does not contain calibration data. It's looking for that optris_imager.yaml file which I can't find. All I have are the calibration files in XML, DAT, and PRN files. Also, topics like the /optris/thermal_image_view is publishing image data, but the /optris/camera_info is publishing 0 for almost everything (e.g. height, width, offsets, etc.).

**Comment by stefanmay** [comment]
This calibration file is for your optics. It has nothing to do with thermal data conversion. You need to perform the calibration for your specific camera on your own, if you desire to do photogrammetric corrections. See here: http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration

**Comment by brianFruit** [comment]
I see what you mean, but shouldn't the mfg provide this yaml file for the Optris Xi 400 thermal camera? I ask because the calibration tutorial you sent only works for RGB camera. The thermal camera will not be able to see the chess board. It seems like I'm still missing something here.

**Comment by stefanmay** [comment]
the vendor does not provide this calibration file. The community cannot do this for you, since this file is individual for each camera. So, it is up to you, to do this calibration. Most users do not need such a calibration. That is why Optris does not feel this is worth spending effort on, which would make the cameras more expensive. For thermal calibration you can find several publications. What you need is a calibration target, on which you can identify patterns in the thermal image.

**Comment by brianFruit** [comment]
Ah, I see. Looks like this yaml file is optional. It makes sense since it's throwing a warning not error. Thanks for the help, @stefanmay!

**Comment by CesarRG002** [comment]
Hi, I have the same issue with an Optris 450 G7 camera. I tried to modify the optris_drivers.launch file in the line 7

` <param name="xmlConfig"      type="string" value="$(find optris_drivers)/config/generic.xml"/> `

and replaced it with my configuration file (serial number of the camera). When I do that it sends me the error: 

> [optris/optris_imager_node-1] process has died [pid 20816, exit code 255, cmd /home/cesarrg/Optris_ws/devel/lib/optris_drivers/optris_imager_node __name:=optris_imager_node __log:=/home/cesarrg/.ros/log/42ed33ec-d7c8-11ea-a3cb-7440bb22240b/optris-optris_imager_node-1.log].
log file: /home/cesarrg/.ros/log/42ed33ec-d7c8-11ea-a3cb-7440bb22240b/optris-optris_imager_node-1*.log

when I keep the generic file it send me the same image than brianFruit but shows no image and no data at all 

Thank you for in advance for your answers.
