### ISSUE TITLE
Duration is out of dual 32-bit range

### ISSUE THREAD

**Issue by saikishor** [evocortex/optris_drivers#30]
```
process[optris/optris_imager_node-1]: started with pid [15942]
process[optris/optris_colorconvert_node-2]: started with pid [15943]
process[optris/image_proc-3]: started with pid [15944]
[IRDeviceParams.cpp:146] @ 9.76562e-07s : Logger not configured!
[ INFO] [1567687589.750177841]: camera calibration URL: file:///tmp/.ros/camera_info/optris_imager.yaml
[ INFO] [1567687589.750259025]: Unable to open camera calibration file [/tmp/.ros/camera_info/optris_imager.yaml]
[ WARN] [1567687589.750284767]: Camera calibration file /tmp/.ros/camera_info/optris_imager.yaml not found.
[ WARN] [1567687589.750303095]: camera_info_url does not contain calibration data.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Duration is out of dual 32-bit range
[optris/optris_imager_node-1] process has died [pid 15942, exit code -6, cmd /home/pal/deployed_ws/lib/optris_drivers/optris_imager_node __name:=optris_imager_node __log:=/home/pal/.ros/log/dd7bea30-cfda-11e9-ac1c-d43b04def328/optris-optris_imager_node-1.log].
log file: /home/pal/.ros/log/dd7bea30-cfda-11e9-ac1c-d43b04def328/optris-optris_imager_node-1*.log
```
When I connect my optris device (Optris PI) and run these drivers, I have the above issue.

```
rosrun optris_drivers optris_imager_node _xmlConfig:=/home/saikishor/ws/src/optris_drivers/config/17040087.xml 
[IRDeviceParams.cpp:146] @ 9.76562e-07s : Logger not configured!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Duration is out of dual 32-bit range
Aborted (core dumped)
```

**Comment by montioo** [comment]
I'm having the same issue with the Xi-400. It looks to me like the error is caused by `ros::Duration(1.0/_imager.getMaxFramerate())` in `OptrisImager::run()` in OptrisImager.cpp. 

`_imager.getMaxFramerate()` returns `0` which isn't a very useful value for a maximum framerate :D This seems to be the case because in the constructor `OptrisImager::OptrisImager(..)` the `IRImager::init(..)` method is called and returns the value `false`, i.e. the initialization failed. This isn't handled or by the OptrisImager class. 

I'm not sure why this error suddenly occurs, as I didn't update libirimager or optris_drivers. I looked into the documentation of libirimager [evo::IRImager::init](http://documentation.evocortex.com/libirimager2/html/classevo_1_1IRImager.html#a1237f3e9100a47f5378cdadb1136521c) but I didn't find any specific information about why the init method failed. One of the linked examples states the reason may be an error with the configuration or the cameras connection to the computer. However, `evo::IRDeviceParams params` and `evo::IRDevice* dev` are created without any errors in optris_imager_node.cpp.

**Comment by saikishor** [comment]
@montioo Exactly, I have the issue at the same place, I came back to this package after an year or so, now it is not working. I have more than one of those cameras, and I am facing this issue suddenly. It is strange to have zero at that parameter.

It would be nice, if the contributor to this package responds to our issue.

**Comment by stefanmay** [comment]
There are plenty of possibilities why the init method could fail. There might be an issue with the uvc interface. This you can check with standard tools, e.g. guvcview. If you receive a green image in the desired update rate, this is fine. Then there could be something wrong with the parameters, you pass. Also the calibration files could be broken or some of them might be missing. Did you activate the log mechanism? How you can do this, is described in the documentation. The init method will print a message before returning with a zero value. Please post this message in order to have a chance to find a solution.

**Comment by saikishor** [comment]
@stefanmay Thank you for the response, I will try to update you about this on Monday.

**Comment by saikishor** [comment]
I use the Troubleshooting section to add the debug line from here :
http://documentation.evocortex.com/libirimager2/html/index.html

After adding the debug line, I have this as output:
```
process[optris/optris_imager_node-2]: started with pid [7838]
process[optris/optris_colorconvert_node-3]: started with pid [7839]
process[optris/image_proc-4]: started with pid [7854]
WARNING [IRDeviceParams.cpp:128] @ 0.00691895s :XML parameter 'pifmode' is deprecated, please use 'pif_in_mode' instead.
DEBUG [IRDeviceParams.cpp:146] @ 0.00694092s :Parameters
DEBUG [IRDeviceParams.cpp:147] @ 0.00694702s :serial: 0
DEBUG [IRDeviceParams.cpp:148] @ 0.00695093s :videoformatindex: 0
DEBUG [IRDeviceParams.cpp:149] @ 0.00695386s :fov: 0
DEBUG [IRDeviceParams.cpp:150] @ 0.00695801s :optics_text: 
DEBUG [IRDeviceParams.cpp:151] @ 0.00696094s :formatspath: /usr/share/libirimager
DEBUG [IRDeviceParams.cpp:152] @ 0.00696484s :calipath: /usr/share/libirimager/cali
DEBUG [IRDeviceParams.cpp:153] @ 0.00696802s :temperature min: 0
DEBUG [IRDeviceParams.cpp:154] @ 0.00697095s :temperature max: 0
DEBUG [IRDeviceParams.cpp:155] @ 0.00697681s :framerate: 32
DEBUG [IRDeviceParams.cpp:156] @ 0.00698193s :bispectral: 0
DEBUG [IRDeviceParams.cpp:157] @ 0.00698682s :average: 0
DEBUG [IRDeviceParams.cpp:158] @ 0.00699097s :flag automatic: 1
DEBUG [IRDeviceParams.cpp:159] @ 0.00699487s :min interval: 15
DEBUG [IRDeviceParams.cpp:160] @ 0.00699902s :max interval: 0
DEBUG [IRDeviceParams.cpp:161] @ 0.00700195s :PIF mode: 0
DEBUG [IRDeviceParams.cpp:162] @ 0.00700488s :chip heating mode: 0
DEBUG [IRDeviceParams.cpp:163] @ 0.00700903s :chip heating fixed val: 40
DEBUG [IRDeviceParams.cpp:164] @ 0.00701196s :focus:  50
INFO [IRDeviceCreate.cpp:23] @ 0.00702197s :Searching for attached device...
DEBUG [UdevHelper.cpp:93] @ 0.107441s :Try opening video device /dev/video0 ... success
DEBUG [IRDeviceUVC.cpp:25] @ 0.107532s :Instantiated ImagerUVC
DEBUG [IRDeviceUVC.cpp:148] @ 0.107559s :OpenDevice
DEBUG [IRDeviceUVC.cpp:174] @ 0.107572s :Try opening video device /dev/video0 ... success
DEBUG [IRDeviceUVC.cpp:207] @ 0.107579s :Stream size: 382 x 290
DEBUG [IRDeviceUVC.cpp:223] @ 0.107583s :Pixelformat: 1448695129, Frequency: 27
DEBUG [IRDeviceUVC.cpp:236] @ 0.107588s :VIDIOC_QUERYCAP successful for PI IMAGER
DEBUG [IRDeviceUVC.cpp:78] @ 0.107835s :initMmap
DEBUG [IRDeviceUVC.cpp:110] @ 0.10791s :mmap request: 4 buffers
DEBUG [Cali.cpp:96] @ 0.107958s :Calibration directory path: /usr/share/libirimager/cali
DEBUG [Cali.cpp:97] @ 0.107966s :Calibration file name: Cali-17040086.xml
DEBUG [SimpleXML.cpp:220] @ 0.10839s :Failed to open file /usr/share/libirimager/cali/Cali-17040086.xml
ERROR [IRImager.cpp:205] @ 0.108404s :Main calibration file missing or inaccessible: /usr/share/libirimager/cali\Cali-17040086.xml
[ INFO] [1568011784.873191076]: camera calibration URL: file:///tmp/.ros/camera_info/optris_imager.yaml
[ INFO] [1568011784.873268782]: Unable to open camera calibration file [/tmp/.ros/camera_info/optris_imager.yaml]
[ WARN] [1568011784.873289740]: Camera calibration file /tmp/.ros/camera_info/optris_imager.yaml not found.
[ WARN] [1568011784.873307432]: camera_info_url does not contain calibration data.
DEBUG [IRDeviceUVC.cpp:305] @ 0.223166s :startStreaming
```

I found that I am missing the xml file in the /usr/share folder, I have all other calibration files, but this is missing.
`DEBUG [SimpleXML.cpp:220] @ 0.10839s :Failed to open file /usr/share/libirimager/cali/Cali-17040086.xml`

@stefanmay Thanks for the help!!.

**Comment by stefanmay** [comment]
I tested the download of your files with the following command:
ir_download_calibration -t /tmp -d 17040086
and find all files (also Cali-17040086.xml) in my /tmp directory.
Would you please attach the camera and execute:
$ sudo ir_download_calibration
and check whether this file is added.

**Comment by saikishor** [comment]
Yes yes I have already executed it, and the camera is working now. @stefanmay

**Comment by montioo** [comment]
@stefanmay thank you for your help. 
After enabling the debug output by calling `evo::IRLogger::setVerbosity(evo::IRLOG_DEBUG, evo::IRLOG_OFF);` at the beginning of my program, it turned out that I had a problem with the file Formats.def. 
```
ERROR [IRImager.cpp:302] @ 0.0833079s :Formats.def file cannot be found. Check configuration of <formatspath> tag and existence of file.
```
My Formats.def file didn't have an entry for the Xi 400 series I was trying to use and my ROS node also wasn't able to read the file because of missing permissions. 
I downloaded a new Formats.def file using the Windows software PIX Connect. In the menu bar click *Tools* -> *Extended* -> *Update format definition file*. The new file was downloaded to *C:\Program Files (x86)\Optris GmbH\PIX Connect* and after I copied the file to my Ubuntu machine and made sure the permissions were sufficient, everything worked again.

**Comment by saikishor** [comment]
@stefanmay @montioo  Thank you for the update on the issue. I will close the issue as both of us have solved our issues. 

Thanks again!!

**Comment by OptrisBeginner** [comment]
Hi, 
I have an issue on XI 400. Anyone can help me please. when I use guvcview, I get a black damaged screen instead for a green screen. 
DEBUG [IRDeviceParams.cpp:164] @ 0.000528076s :Parameters
DEBUG [IRDeviceParams.cpp:165] @ 0.000628906s :serial: 19104157
DEBUG [IRDeviceParams.cpp:166] @ 0.000716064s :videoformatindex: 0
DEBUG [IRDeviceParams.cpp:167] @ 0.000751953s :fov: 80
DEBUG [IRDeviceParams.cpp:168] @ 0.000774902s :optics_text: 
DEBUG [IRDeviceParams.cpp:169] @ 0.000804932s :formatspath: /usr/share/libirimager
DEBUG [IRDeviceParams.cpp:170] @ 0.000828857s :calipath: /usr/share/libirimager/cali
DEBUG [IRDeviceParams.cpp:171] @ 0.00085791s :temperature min: 0
DEBUG [IRDeviceParams.cpp:172] @ 0.000880859s :temperature max: 250
DEBUG [IRDeviceParams.cpp:173] @ 0.000916992s :framerate: 32
DEBUG [IRDeviceParams.cpp:174] @ 0.000968994s :bispectral: 0
DEBUG [IRDeviceParams.cpp:175] @ 0.00101685s :average: 0
DEBUG [IRDeviceParams.cpp:176] @ 0.00106104s :flag automatic: 1
DEBUG [IRDeviceParams.cpp:177] @ 0.00110889s :min interval: 15
DEBUG [IRDeviceParams.cpp:178] @ 0.00115503s :max interval: 0
DEBUG [IRDeviceParams.cpp:179] @ 0.00123999s :chip heating mode: 0
DEBUG [IRDeviceParams.cpp:180] @ 0.00128491s :chip heating fixed val: 40
DEBUG [IRDeviceParams.cpp:181] @ 0.00132007s :focus:  50
DEBUG [IRDeviceParams.cpp:182] @ 0.00135498s :enable extended temp range: 0
DEBUG [IRDeviceParams.cpp:183] @ 0.00138794s :buffer queue size: 5
DEBUG [IRDeviceParams.cpp:184] @ 0.00141895s :enable high precision: 0
INFO [IRDeviceCreate.cpp:33] @ 0.00146387s :Searching for attached device...
DEBUG [UdevHelper.cpp:93] @ 0.0897371s :Try opening video device /dev/video0 ... success
DEBUG [IRDeviceUVC.cpp:25] @ 0.0912939s :Instantiated ImagerUVC
DEBUG [IRDeviceUVC.cpp:148] @ 0.0913489s :OpenDevice
DEBUG [IRDeviceUVC.cpp:174] @ 0.0913789s :Try opening video device /dev/video0 ... success
DEBUG [IRDeviceUVC.cpp:207] @ 0.091395s :Stream size: 382 x 290
DEBUG [IRDeviceUVC.cpp:223] @ 0.0914199s :Pixelformat: 1448695129, Frequency: 27
DEBUG [IRDeviceUVC.cpp:236] @ 0.091437s :VIDIOC_QUERYCAP successful for Xi IMAGER: Xi IMAGER
DEBUG [IRDeviceUVC.cpp:78] @ 0.118896s :initMmap
DEBUG [IRDeviceUVC.cpp:110] @ 0.119096s :mmap request: 5 buffers
DEBUG [Cali.cpp:97] @ 0.119284s :Calibration directory path: /usr/share/libirimager/cali
DEBUG [Cali.cpp:98] @ 0.119315s :Calibration file name: Cali-19104157.xml
DEBUG [Cali.cpp:108] @ 0.119397s :Calibration data A: 1450 B:400 C:4095 D:1000
INFO [IRImager.cpp:272] @ 0.119526s :Init thermal imager with size: 382x290@27 Hz
DEBUG [IRImager.cpp:378] @ 0.119631s :Using HID control interface
DEBUG [IRImager.cpp:1274] @ 0.211813s :Set focusmotor position to 50 %
DEBUG [IRImager.cpp:424] @ 0.211882s :Frameconfig - width(in): 382, height(in): 290, interval: 370370, max framerate: 27, HW interval: 0.037037
DEBUG [ImageProcessing.cpp:178] @ 0.225151s :Source buffer size: 221560 Width: 382 Height: 290
DEBUG [OpSource.cpp:332] @ 0.267198s :Using formats path: /usr/share/libirimager/Formats.def
DEBUG [OpSource.cpp:561] @ 0.267397s :Format found with size: 382
DEBUG [OpSource.cpp:332] @ 0.267449s :Using formats path: /usr/share/libirimager/Formats.def
DEBUG [ImageProcessing.cpp:109] @ 0.272848s :Source buffer size: 221560 Width: 382 Height: 290
DEBUG [OpSource.cpp:332] @ 0.272916s :Using formats path: /usr/share/libirimager/Formats.def
DEBUG [OpSource.cpp:561] @ 0.273068s :Format found with size: 382
DEBUG [IRImager.cpp:812] @ 0.273818s :Caught onFrameInit with size: 382x288
DEBUG [OpCorr.cpp:440] @ 0.275825s :Read cali: /usr/share/libirimager/cali/Cali-19104157-80-0-250.dat
DEBUG [OpCorr.cpp:530] @ 0.275874s :Read calibration of camera no 19104157, # of fields: 6 , start of fields: 40
DEBUG [ImageProcessing.cpp:949] @ 0.604114s :Update flag temperature: 34.5
DEBUG [ImageProcessing.cpp:952] @ 0.6093s :Update box temperature: 34.4375
DEBUG [IRImager.cpp:522] @ 0.622933s :Chip heating disabled
DEBUG [IRDeviceUVC.cpp:305] @ 0.629945s :startStreaming
DEBUG [IRDeviceUVC.cpp:305] @ 10.6479s :startStreaming
ERROR [IRDeviceUVC.cpp:320] @ 10.6479s :Error in queuing buffer: Invalid argument index: 0
ERROR [IRDeviceUVC.cpp:320] @ 10.648s :Error in queuing buffer: Invalid argument index: 1
ERROR [IRDeviceUVC.cpp:320] @ 10.648s :Error in queuing buffer: Invalid argument index: 2
ERROR [IRDeviceUVC.cpp:320] @ 10.6481s :Error in queuing buffer: Invalid argument index: 3
ERROR [IRDeviceUVC.cpp:320] @ 10.6481s :Error in queuing buffer: Invalid argument index: 4
DEBUG [IRDeviceUVC.cpp:428] @ 20.858s :Select error
DEBUG [OpMetadata.cpp:86] @ 20.8635s :Possible data corruption: 0 0 0 86.926
DEBUG [IRDeviceUVC.cpp:428] @ 21.0682s :Select error
DEBUG [IRDeviceUVC.cpp:428] @ 21.2693s :Select error

I think I have correct xml and Formats.def files but the startStream doesn't work.

**Comment by CesarRG002** [comment]
Hi, I'm currently working with a Optris PI 450 G7 camera in a Ubuntu Melodic. I did implement the launch file with the configuration file, and when I launch it shows me the same line that your

```
process[optris/optris_imager_node-1]: started with pid [20397]
process[optris/optris_colorconvert_node-2]: started with pid [20398]
[IRDeviceParams.cpp:186] @ 1.95312e-06s : Logger not configured!
process[optris/image_proc-3]: started with pid [20403]
[ INFO] [1597662351.484861348]: camera calibration URL: file:///tmp/.ros/camera_info/optris_imager.yaml
[ INFO] [1597662351.485465074]: Unable to open camera calibration file [/tmp/.ros/camera_info/optris_imager.yaml]
[ WARN] [1597662351.485490363]: Camera calibration file /tmp/.ros/camera_info/optris_imager.yaml not found.
[ WARN] [1597662351.485518422]: camera_info_url does not contain calibration data.
```
so same "error" **[IRDeviceParams.cpp:186] @ 1.95312e-06s : Logger not configured!**

My question is where did you add the debug line? I read the Troubleshooting guide says at the beginning of your application but I've already add it: 

 - At the beginning of the file "optris_imager_node.cpp"
- At the beginning of the file "optris_colorconvert_node.cpp"
- At the beginning of the launch file 
- At the beginning line before running the launch
- At the beginning line before running rosrun optris_drivers optris_imager_node _xmlConfig:=/home/cesarrg/OptrisThem_ws/src/optris_drivers/config/15040011.xml

and in all of this solutions I got 2 answers, either the terminal show me 2 options:

- bash: syntax error near unexpected token `('
- or it keeps in this message: [IRDeviceParams.cpp:186] @ 1.95312e-06s : Logger not configured! for an undefined time

May you please help me or at leat explain me where did you add the debug line. Thank you in advance.

Also. I'm triying to visualize the image of the camera. To do this I'm trying with rviz and with the own nodes of Optris:
   
` rosrun image_view image_view image:=/optris/thermal_image_view`

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////77
> I use the Troubleshooting section to add the debug line from here :
> http://documentation.evocortex.com/libirimager2/html/index.html
> 
> After adding the debug line, I have this as output:
> 
> ```
> process[optris/optris_imager_node-2]: started with pid [7838]
> process[optris/optris_colorconvert_node-3]: started with pid [7839]
> process[optris/image_proc-4]: started with pid [7854]
> WARNING [IRDeviceParams.cpp:128] @ 0.00691895s :XML parameter 'pifmode' is deprecated, please use 'pif_in_mode' instead.
> DEBUG [IRDeviceParams.cpp:146] @ 0.00694092s :Parameters
> DEBUG [IRDeviceParams.cpp:147] @ 0.00694702s :serial: 0
> DEBUG [IRDeviceParams.cpp:148] @ 0.00695093s :videoformatindex: 0
> DEBUG [IRDeviceParams.cpp:149] @ 0.00695386s :fov: 0
> DEBUG [IRDeviceParams.cpp:150] @ 0.00695801s :optics_text: 
> DEBUG [IRDeviceParams.cpp:151] @ 0.00696094s :formatspath: /usr/share/libirimager
> DEBUG [IRDeviceParams.cpp:152] @ 0.00696484s :calipath: /usr/share/libirimager/cali
> DEBUG [IRDeviceParams.cpp:153] @ 0.00696802s :temperature min: 0
> DEBUG [IRDeviceParams.cpp:154] @ 0.00697095s :temperature max: 0
> DEBUG [IRDeviceParams.cpp:155] @ 0.00697681s :framerate: 32
> DEBUG [IRDeviceParams.cpp:156] @ 0.00698193s :bispectral: 0
> DEBUG [IRDeviceParams.cpp:157] @ 0.00698682s :average: 0
> DEBUG [IRDeviceParams.cpp:158] @ 0.00699097s :flag automatic: 1
> DEBUG [IRDeviceParams.cpp:159] @ 0.00699487s :min interval: 15
> DEBUG [IRDeviceParams.cpp:160] @ 0.00699902s :max interval: 0
> DEBUG [IRDeviceParams.cpp:161] @ 0.00700195s :PIF mode: 0
> DEBUG [IRDeviceParams.cpp:162] @ 0.00700488s :chip heating mode: 0
> DEBUG [IRDeviceParams.cpp:163] @ 0.00700903s :chip heating fixed val: 40
> DEBUG [IRDeviceParams.cpp:164] @ 0.00701196s :focus:  50
> INFO [IRDeviceCreate.cpp:23] @ 0.00702197s :Searching for attached device...
> DEBUG [UdevHelper.cpp:93] @ 0.107441s :Try opening video device /dev/video0 ... success
> DEBUG [IRDeviceUVC.cpp:25] @ 0.107532s :Instantiated ImagerUVC
> DEBUG [IRDeviceUVC.cpp:148] @ 0.107559s :OpenDevice
> DEBUG [IRDeviceUVC.cpp:174] @ 0.107572s :Try opening video device /dev/video0 ... success
> DEBUG [IRDeviceUVC.cpp:207] @ 0.107579s :Stream size: 382 x 290
> DEBUG [IRDeviceUVC.cpp:223] @ 0.107583s :Pixelformat: 1448695129, Frequency: 27
> DEBUG [IRDeviceUVC.cpp:236] @ 0.107588s :VIDIOC_QUERYCAP successful for PI IMAGER
> DEBUG [IRDeviceUVC.cpp:78] @ 0.107835s :initMmap
> DEBUG [IRDeviceUVC.cpp:110] @ 0.10791s :mmap request: 4 buffers
> DEBUG [Cali.cpp:96] @ 0.107958s :Calibration directory path: /usr/share/libirimager/cali
> DEBUG [Cali.cpp:97] @ 0.107966s :Calibration file name: Cali-17040086.xml
> DEBUG [SimpleXML.cpp:220] @ 0.10839s :Failed to open file /usr/share/libirimager/cali/Cali-17040086.xml
> ERROR [IRImager.cpp:205] @ 0.108404s :Main calibration file missing or inaccessible: /usr/share/libirimager/cali\Cali-17040086.xml
> [ INFO] [1568011784.873191076]: camera calibration URL: file:///tmp/.ros/camera_info/optris_imager.yaml
> [ INFO] [1568011784.873268782]: Unable to open camera calibration file [/tmp/.ros/camera_info/optris_imager.yaml]
> [ WARN] [1568011784.873289740]: Camera calibration file /tmp/.ros/camera_info/optris_imager.yaml not found.
> [ WARN] [1568011784.873307432]: camera_info_url does not contain calibration data.
> DEBUG [IRDeviceUVC.cpp:305] @ 0.223166s :startStreaming
> ```
> 
> I found that I am missing the xml file in the /usr/share folder, I have all other calibration files, but this is missing.
> `DEBUG [SimpleXML.cpp:220] @ 0.10839s :Failed to open file /usr/share/libirimager/cali/Cali-17040086.xml`
> 
> @stefanmay Thanks for the help!!.

**Comment by stefanmay** [comment]
Dear Cesar,

please run the download command for the calibration files:
$ sudo ir_download_calibration
, while the camera is attached.
Alternatively:
$ sudo ir_download_calibration -d17040086
Then you should find the missing file.

Best regards,
   Stefan May

**Comment by EXPX3** [comment]
@stefanmay 
We have purchased the Optris PI 450 and trying to run it with ROS nodes, can you Kindly guide me through this...

1. I downloaded the calibration files for my device. They are at /usr/share/libirimager/cali/  and the file name is Cali-13090046.xml
why am i getting this warning below? although i have the files in correct location.

[ WARN] [1622302715.998043461]: Camera calibration file /usr/share/libirimager/cali/Cali-13090046.xml not found.
[ WARN] [1622302715.998321981]: camera_info_url does not contain calibration data.

2.  Can you kindly help me give an idea of how to understand the following DEBUG lines, is the thermal camera data already being published?

DEBUG [IRDeviceUVC.cpp:305] @ 0.648503s :startStreaming
DEBUG [IRDeviceUVC.cpp:468] @ 0.726781s :Incomplete frame transmission, bytes: 221760, width: 385, height: 289
DEBUG [IRImager.cpp:1102] @ 0.770629s :Start flag calibration
DEBUG [IRImager.cpp:1116] @ 3.8408s :Finished startup calibration
DEBUG [IRImager.cpp:1167] @ 18.8848s :Automatic control of shutter flag
DEBUG [OpFlag.cpp:591] @ 19.3294s :SkimDiff: 0 Adjust: 0 State: 0 EMax: 9309 Emin: 4221
DEBUG [IRImager.cpp:1167] @ 33.9216s :Automatic control of shutter flag
DEBUG [OpFlag.cpp:591] @ 34.3658s :SkimDiff: 0 Adjust: 0 State: 0 EMax: 9305 Emin: 4181

3. when i run guvcview i have my thermal camera showing green screen.
should i run the thermal optris_imager_node and the guvcview simultaneously?  or how do i visualize the thermal camera image on guvcview? Or if guvcview is just a check to see if thermal camera is outputing raw data? . To visualize the thermal camera output in ros i understand that following node is used.  
$ rosrun image_view image_view image:=/optris/thermal_image_view 

But when i run it i get the following ..  
[ INFO] [1622306152.330482232]: Initializing nodelet with 4 worker threads.
[ INFO] [1622306152.480652359]: Using transport "raw"

**Comment by EXPX3** [comment]
> Hi, I'm currently working with a Optris PI 450 G7 camera in a Ubuntu Melodic. I did implement the launch file with the configuration file, and when I launch it shows me the same line that your
> 
> ```
> process[optris/optris_imager_node-1]: started with pid [20397]
> process[optris/optris_colorconvert_node-2]: started with pid [20398]
> [IRDeviceParams.cpp:186] @ 1.95312e-06s : Logger not configured!
> process[optris/image_proc-3]: started with pid [20403]
> [ INFO] [1597662351.484861348]: camera calibration URL: file:///tmp/.ros/camera_info/optris_imager.yaml
> [ INFO] [1597662351.485465074]: Unable to open camera calibration file [/tmp/.ros/camera_info/optris_imager.yaml]
> [ WARN] [1597662351.485490363]: Camera calibration file /tmp/.ros/camera_info/optris_imager.yaml not found.
> [ WARN] [1597662351.485518422]: camera_info_url does not contain calibration data.
> ```
> 
> so same "error" **[IRDeviceParams.cpp:186] @ 1.95312e-06s : Logger not configured!**
> 
> My question is where did you add the debug line? I read the Troubleshooting guide says at the beginning of your application but I've already add it:
> 
>     * At the beginning of the file "optris_imager_node.cpp"
> 
>     * At the beginning of the file "optris_colorconvert_node.cpp"
> 
>     * At the beginning of the launch file
> 
>     * At the beginning line before running the launch
> 
>     * At the beginning line before running rosrun optris_drivers optris_imager_node _xmlConfig:=/home/cesarrg/OptrisThem_ws/src/optris_drivers/config/15040011.xml
> 
> 
> and in all of this solutions I got 2 answers, either the terminal show me 2 options:
> 
>     * bash: syntax error near unexpected token `('
> 
>     * or it keeps in this message: [IRDeviceParams.cpp:186] @ 1.95312e-06s : Logger not configured! for an undefined time
> 
> 
> May you please help me or at leat explain me where did you add the debug line. Thank you in advance.
> 
> Also. I'm triying to visualize the image of the camera. To do this I'm trying with rviz and with the own nodes of Optris:
> 
> ` rosrun image_view image_view image:=/optris/thermal_image_view`
> 
> //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////77
> 
> > I use the Troubleshooting section to add the debug line from here :
> > http://documentation.evocortex.com/libirimager2/html/index.html
> > After adding the debug line, I have this as output:
> > ```
> > process[optris/optris_imager_node-2]: started with pid [7838]
> > process[optris/optris_colorconvert_node-3]: started with pid [7839]
> > process[optris/image_proc-4]: started with pid [7854]
> > WARNING [IRDeviceParams.cpp:128] @ 0.00691895s :XML parameter 'pifmode' is deprecated, please use 'pif_in_mode' instead.
> > DEBUG [IRDeviceParams.cpp:146] @ 0.00694092s :Parameters
> > DEBUG [IRDeviceParams.cpp:147] @ 0.00694702s :serial: 0
> > DEBUG [IRDeviceParams.cpp:148] @ 0.00695093s :videoformatindex: 0
> > DEBUG [IRDeviceParams.cpp:149] @ 0.00695386s :fov: 0
> > DEBUG [IRDeviceParams.cpp:150] @ 0.00695801s :optics_text: 
> > DEBUG [IRDeviceParams.cpp:151] @ 0.00696094s :formatspath: /usr/share/libirimager
> > DEBUG [IRDeviceParams.cpp:152] @ 0.00696484s :calipath: /usr/share/libirimager/cali
> > DEBUG [IRDeviceParams.cpp:153] @ 0.00696802s :temperature min: 0
> > DEBUG [IRDeviceParams.cpp:154] @ 0.00697095s :temperature max: 0
> > DEBUG [IRDeviceParams.cpp:155] @ 0.00697681s :framerate: 32
> > DEBUG [IRDeviceParams.cpp:156] @ 0.00698193s :bispectral: 0
> > DEBUG [IRDeviceParams.cpp:157] @ 0.00698682s :average: 0
> > DEBUG [IRDeviceParams.cpp:158] @ 0.00699097s :flag automatic: 1
> > DEBUG [IRDeviceParams.cpp:159] @ 0.00699487s :min interval: 15
> > DEBUG [IRDeviceParams.cpp:160] @ 0.00699902s :max interval: 0
> > DEBUG [IRDeviceParams.cpp:161] @ 0.00700195s :PIF mode: 0
> > DEBUG [IRDeviceParams.cpp:162] @ 0.00700488s :chip heating mode: 0
> > DEBUG [IRDeviceParams.cpp:163] @ 0.00700903s :chip heating fixed val: 40
> > DEBUG [IRDeviceParams.cpp:164] @ 0.00701196s :focus:  50
> > INFO [IRDeviceCreate.cpp:23] @ 0.00702197s :Searching for attached device...
> > DEBUG [UdevHelper.cpp:93] @ 0.107441s :Try opening video device /dev/video0 ... success
> > DEBUG [IRDeviceUVC.cpp:25] @ 0.107532s :Instantiated ImagerUVC
> > DEBUG [IRDeviceUVC.cpp:148] @ 0.107559s :OpenDevice
> > DEBUG [IRDeviceUVC.cpp:174] @ 0.107572s :Try opening video device /dev/video0 ... success
> > DEBUG [IRDeviceUVC.cpp:207] @ 0.107579s :Stream size: 382 x 290
> > DEBUG [IRDeviceUVC.cpp:223] @ 0.107583s :Pixelformat: 1448695129, Frequency: 27
> > DEBUG [IRDeviceUVC.cpp:236] @ 0.107588s :VIDIOC_QUERYCAP successful for PI IMAGER
> > DEBUG [IRDeviceUVC.cpp:78] @ 0.107835s :initMmap
> > DEBUG [IRDeviceUVC.cpp:110] @ 0.10791s :mmap request: 4 buffers
> > DEBUG [Cali.cpp:96] @ 0.107958s :Calibration directory path: /usr/share/libirimager/cali
> > DEBUG [Cali.cpp:97] @ 0.107966s :Calibration file name: Cali-17040086.xml
> > DEBUG [SimpleXML.cpp:220] @ 0.10839s :Failed to open file /usr/share/libirimager/cali/Cali-17040086.xml
> > ERROR [IRImager.cpp:205] @ 0.108404s :Main calibration file missing or inaccessible: /usr/share/libirimager/cali\Cali-17040086.xml
> > [ INFO] [1568011784.873191076]: camera calibration URL: file:///tmp/.ros/camera_info/optris_imager.yaml
> > [ INFO] [1568011784.873268782]: Unable to open camera calibration file [/tmp/.ros/camera_info/optris_imager.yaml]
> > [ WARN] [1568011784.873289740]: Camera calibration file /tmp/.ros/camera_info/optris_imager.yaml not found.
> > [ WARN] [1568011784.873307432]: camera_info_url does not contain calibration data.
> > DEBUG [IRDeviceUVC.cpp:305] @ 0.223166s :startStreaming
> > ```
> > 
> > 
> > I found that I am missing the xml file in the /usr/share folder, I have all other calibration files, but this is missing.
> > `DEBUG [SimpleXML.cpp:220] @ 0.10839s :Failed to open file /usr/share/libirimager/cali/Cali-17040086.xml`
> > @stefanmay Thanks for the help
@CesarRG002  after adding the debug line in the source code, i did catkin_make. Only then is the "logger not configured!" error disappears and debug texts follow,

**Comment by EXPX3** [comment]
> @stefanmay
> We have purchased the Optris PI 450 and trying to run it with ROS nodes, can you Kindly guide me through this...
> 
>     1. I downloaded the calibration files for my device. They are at /usr/share/libirimager/cali/  and the file name is Cali-13090046.xml
>        why am i getting this warning below? although i have the files in correct location.
> 
> 
> [ WARN] [1622302715.998043461]: Camera calibration file /usr/share/libirimager/cali/Cali-13090046.xml not found.
> [ WARN] [1622302715.998321981]: camera_info_url does not contain calibration data.
> 
>     1. Can you kindly help me give an idea of how to understand the following DEBUG lines, is the thermal camera data already being published?
> 
> 
> DEBUG [IRDeviceUVC.cpp:305] @ 0.648503s :startStreaming
> DEBUG [IRDeviceUVC.cpp:468] @ 0.726781s :Incomplete frame transmission, bytes: 221760, width: 385, height: 289
> DEBUG [IRImager.cpp:1102] @ 0.770629s :Start flag calibration
> DEBUG [IRImager.cpp:1116] @ 3.8408s :Finished startup calibration
> DEBUG [IRImager.cpp:1167] @ 18.8848s :Automatic control of shutter flag
> DEBUG [OpFlag.cpp:591] @ 19.3294s :SkimDiff: 0 Adjust: 0 State: 0 EMax: 9309 Emin: 4221
> DEBUG [IRImager.cpp:1167] @ 33.9216s :Automatic control of shutter flag
> DEBUG [OpFlag.cpp:591] @ 34.3658s :SkimDiff: 0 Adjust: 0 State: 0 EMax: 9305 Emin: 4181
> 
>     1. when i run guvcview i have my thermal camera showing green screen.
>        should i run the thermal optris_imager_node and the guvcview simultaneously?  or how do i visualize the thermal camera image on guvcview? Or if guvcview is just a check to see if thermal camera is outputing raw data? . To visualize the thermal camera output in ros i understand that following node is used.
>        $ rosrun image_view image_view image:=/optris/thermal_image_view
> 
> 
> But when i run it i get the following ..
> [ INFO] [1622306152.330482232]: Initializing nodelet with 4 worker threads.
> [ INFO] [1622306152.480652359]: Using transport "raw"

@stefanmay  I understood that the debug lines starting with [WARN] do not stop the device from functioning.
After running the command "rosrun image_view image_view image:=/optris/thermal_image_view" I had top be a bit patient until i get the output of the thermal camera. Now i have the output. But still would like to have a feedback on my questions 1 and 2. Thankyou.
