### ISSUE TITLE
Warning during startup 

### ISSUE THREAD

**Issue by OptrisBeginner** [evocortex/optris_drivers#35]
Hi, 

Anyone have an idea, what following warnings mean? and why do we get these?
Warnings appears on startup of IRCamera. I am using XI400. 
 
ERROR [OpFlag.cpp:396] @ 14.1854s :ImagerError_FlagTooShort
ERROR [OpFlag.cpp:145] @ 13.3229s :ImagerError_FlagTimeout
[IRDeviceParams.cpp:164] @ 5.29785e-05s : Logger not configured!

Thanks

**Comment by greekgothguy** [comment]
_ERROR [OpFlag.cpp:396] @ 14.1854s :ImagerError_FlagTooShort
ERROR [OpFlag.cpp:145] @ 13.3229s :ImagerError_FlagTimeout_

This error occures when the framerate, that is being recieved, is too low.

[activating nodrop can help](http://documentation.evocortex.com/libirimager2/html/Installation.html#:~:text=The%20nodrop%20option%20can%20be%20passed%20at%20system%20startup%20by%20creating%20the%20following%20file%3A)
