### ISSUE TITLE
Issue with /optris/thermal_image topics/data

### ISSUE THREAD

**Issue by lchop** [evocortex/optris_drivers#38]
Hello,

From a previous issue, I have compute the temperature for every pixel using this formula:
 
value = 1024 + x 
temp = (value -1000) / 10

```
memcpy(&_thermal_image.data[0], image, w * h * sizeof(*image));
  float mean = 0;
  for (int y = 0; y < h; y = y + 2)
  {
    for (int x = 0; x < w; x = x + 2)
    {
      if (_thermal_image.data[y*w + x +1] == 4)
        mean += _thermal_image.data[y*w + x];
    }
  }
  ROS_INFO_STREAM("mean " << (((mean/(w*h)) + 1024) -1000));
```

This works when the data is an alternation of 4 & 2xx values, but sometimes, I have an alternation of  8 &2xx values, or 5 & xx values. Is this a problem from the camera ? Or should I interprete the values a different way ? Should the data not always be an alternation of 4 & 2xx ?Could you help me ?
Thanks

**Comment by HelmutE89** [comment]
You should interpret/cast the _thermal_image.data[0] as a unsigned short pointer (16 Bit, value range from 0-65535) and increment the for-loop by one. With this unsigend short value the upper formular can be applied.
