### ISSUE TITLE
No Thermal Image

### ISSUE THREAD

**Issue by CesarRG002** [evocortex/optris_drivers#39]
Hi, my name is César and  I'm working with a Optris PI 450 G7 camera in Ubuntu melodic. I think I have manage not so bad to install the dependencies and configure the workspace. Still when I launch the launch file (after configured everything with my camera info) I get no image of the camera. 

I check the nodes info with rqt_graph and get the following 

![Screenshot from 2020-08-17 14-21-04](https://user-images.githubusercontent.com/69304443/90397143-af108380-e097-11ea-8be4-1b2081c37c09.png)

So I run rviz to confirm but I got no Image at all neither from the camera not for the image topics (I tried in all the Transport Hints, specially in the 2 suggested: Raw and Compress and the status is the same No image received. 

but the following error when I run the configuration of the topic thermal_image_view it compressed mode
```
`
[ERROR] [1597667685.153755028]: Tried to advertise a service that is already advertised in this node [/rviz_1597667604952139197/compressed/set_parameters]`

```

when I run the lauch I got the following warning, just as issue #18 shows (I also make a question there, no answer yet)

```
setting /run_id to 301216aa-e085-11ea-9c2f-7440bb22240b
process[rosout-1]: started with pid [27334]
started core service [/rosout]
process[optris/optris_imager_node-2]: started with pid [27341]
process[optris/optris_colorconvert_node-3]: started with pid [27342]
[IRDeviceParams.cpp:186] @ 1.95312e-06s : Logger not configured!
process[optris/image_proc-4]: started with pid [27347]
[ INFO] [1597667323.569505802]: camera calibration URL: file:///tmp/.ros/camera_info/optris_imager.yaml
[ INFO] [1597667323.570372268]: Unable to open camera calibration file [/tmp/.ros/camera_info/optris_imager.yaml]
[ WARN] [1597667323.570409076]: Camera calibration file /tmp/.ros/camera_info/optris_imager.yaml not found.
[ WARN] [1597667323.570435092]: camera_info_url does not contain calibration data.
```

What I found weird is that the nodes are actually working but without transmitting information. Can anyone help me to get the image for the thermal camera? Thank in advance.

**Comment by stefanmay** [comment]
Dear Cesar,

before we can come down to a ROS node issue, we need to check whether the bare examples are working. Did you succeed to run irimager_show?

Best regards,
   Stefan May

**Comment by CesarRG002** [comment]
Dear Stefan, 

 thanks for the advice it did worked the irimager_show :D :+1:  I only need to add the correct path for the xml file. Thanks a lot 


Best Regards,
César

**Comment by HelmutE89** [comment]
Dear César,

great to hear Stefan could solve your issue! I will therefore close this.

Best regards,
Helmut
