### ISSUE TITLE
How to disable Non-Uniformity Correction?

### ISSUE THREAD

**Issue by yunxdai** [evocortex/optris_drivers#42]
I noticed that the camera had NUC mechanism, but I want to disable it since it stuck the image for 1-2 seconds. So is there any interface provided to disable NUC?

**Comment by greekgothguy** [comment]
Changing autoflag, in the .xml file, to 0, disables the NUC 

```
 <autoflag>
  <enable>change this to 0</enable>
  <mininterval>15.0</mininterval>
  <maxinterval>0.0</maxinterval>
 </autoflag>
```

Deactivating this can cause wrong temperatures with time.
