### ISSUE TITLE
How to stop normalisation in every frame?

### ISSUE THREAD

**Issue by aditdoshi333** [evocortex/optris_drivers#43]
Hello,

I am using optris ros package. Currently it is normalising every frame when I run ros node but everything works well with opengl example. Attaching the sample output from ros rviz.

Frames are flickering a lot. I tried disabling auto flag but the result is still the same. 

https://user-images.githubusercontent.com/23434856/137317727-f0258b4c-930b-4a26-95c7-9549dc7cb800.mp4

**Comment by stefanmay** [comment]
This is not an issue with the flag, but with the color conversion. By default the "eMinMax" strategy is enabled. That means the color space is scaled to the minimum and maximum temperature that you see in the image. Look out for the following lines in the conversion node's code:

  int palette = 6;
  n_.getParam("palette", palette);

  evo::EnumOptrisPaletteScalingMethod scalingMethod = evo::eMinMax;
  int sm;
  n_.getParam("paletteScaling", sm);
  if(sm>=1 && sm <=4) scalingMethod = (evo::EnumOptrisPaletteScalingMethod) sm;

  _iBuilder.setPaletteScalingMethod(scalingMethod);
  _iBuilder.setPalette((evo::EnumOptrisColoringPalette)palette);

and adjust the desired scaling method.
